### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by limeb** [z-pattern-matching/z#15]
What is the browser support?

**Comment by leonardiwagner** [comment]
Hi @limeblack , sorry for late response, the only thing we require to run from es2015 is `default parameters`, so it won't run on Internet Explorer, only on Edge, Firefox > 15, Safari > 10, Chrome > 49, basically versions from a year ago

The question is good since there is no attention to run on web, I'll look to improve documentation, and look how it'd works with transpilers such babel.
