### ISSUE TITLE
Source code question

### ISSUE THREAD

**Issue by pvorona** [z-pattern-matching/z#28]
Hello, I've been browsing through source code trying to understand how the thing works and got question considering following function:
```
const matches = (subjectToMatch) =>
  function () {
    const functions = Object.keys(arguments).map(key => arguments[key])

    return resolveMatchFunctions(subjectToMatch, functions)
  }
```
Could you explain why is it using Object.keys / arguments instead of using rest args?
```
const matches = (subjectToMatch) => (...functions) => 
  resolveMatchFunctions(subjectToMatch, functions)
```

I cant find any test explaining this thing.

**Comment by leonardiwagner** [comment]
@pvorona The use of `Object.keys` instead rest parameters, it was because at written time we was compatible with previous versions of node 6 also. Now there is no reason.

You also changed from `function` to a lambda `() =>` in your example. I remember we had a reason to maintain `function` probably due lack of lambda own scope, but honestly I can't remember right now the reason. If we remove this also and tests pass, a PR to update this code is welcomed.

**Comment by pvorona** [comment]
@leonardiwagner Thanks for very fast reply. Tests are OK
https://github.com/z-pattern-matching/z/pull/29
