### ISSUE TITLE
You're accidentally stealing a name and logo

### ISSUE THREAD

**Issue by StoneCypher** [z-pattern-matching/z#48]
There's already something in active use called `z` and it has a very similar logo

It's a mathematical constraint system for proving software, and a big chunk of it is about pattern matching

When `golang` took the same name as the existing high quality language `go`, the existing language disappeared forever, despite that it had several compilers and books

Please consider renaming your project.  `The Way of Z` deserves to live, and [formal methods are already much too rare](https://www.amazon.com/Way-Practical-Programming-Formal-Methods/dp/0521559766)

**Comment by StoneCypher** [comment]
It's actually a fascinating work

Please be considerate and don't bury it forever

![image](https://user-images.githubusercontent.com/77482/42736052-d6c9bf74-8813-11e8-9771-79090e74d356.png)

**Comment by leonardiwagner** [comment]
Hey John, claiming that I stole something was very harsh to hear. I'm only replying to you as a professional colleague, considering you were way too passionate when you wrote that, so I'm not even defending myself of such charges, just replying a friend, okay?

Z is the 26th letter of the Latin alphabet. It isn't a creation of Jonathan Jacky. We can create an idea, a logo, or a font, but not a letter of the alphabet. Since we both used the letter Z from Latin alphabet to name our ideas, it isn't a surprise that we both used the letter Z as cover art.

This project is not "mine" is for the community, it isn't even located at my personal profile, I just created the first commit and named it as Z ( again, a letter from the Latin alphabet), I did not steal, copy, borrow or use any creative idea from other human being, so I'm not going to rename this project for that reason.

**Comment by StoneCypher** [comment]
did you miss the word "accidentally?"  there was no passion here

.

> I did not steal, copy, borrow or use any creative idea from other human being, so I'm not going to rename this project for that reason.

by this choice, you doom either their project or yours

how unfortunate

**Comment by StoneCypher** [comment]
they're in exceptionally similar domains

it's unfortunate that you're arguing about something you don't use

**Comment by StoneCypher** [comment]
oh well.

the golang people reacted almost identically.
